services:
  qps-counter:
    image: qps-counter:latest
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - "8080-8082:8080"
    volumes:
      - ${PWD}/logs:/var/log/qps-counter:rw
    environment:
      - QPS_SERVER_PORT=8080
      - QPS_LOGGER_LEVEL=info
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      rollback_config:
        parallelism: 0
        failure_action: rollback
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3