server:
  port: 8080
  read_timeout: 5s
  write_timeout: 10s
  server_type: fasthttp

counter:
  type: "lockfree"     # 计数器类型（lockfree/sharded）
  window_size: 1s      # 统计时间窗口
  slot_num: 10         # 窗口分片数量
  precision: 100ms     # 统计精度

limiter:
  enabled: true        # 是否启用限流
  rate: 1000000        # 每秒允许的请求数
  burst: 10000         # 突发请求容量
  adaptive: true       # 是否启用自适应限流

metrics:
  enabled: true        # 是否启用指标收集
  interval: 5s         # 指标收集间隔
  endpoint: "/metrics" # 指标暴露端点

shutdown:
  timeout: 30s         # 优雅关闭超时时间
  max_wait: 60s        # 最大等待时间

logger:
  level: info
  format: json
  file_path: "/var/log/qps-counter/app.log"
  max_size: 100
  max_backups: 3
  max_age: 7